### ISSUE TITLE
Wallpapers appear in the same order each time?

### ISSUE THREAD

**Issue by aebrer** [deepjyoti30/QuickWall#1]

**Comment by deepjyoti30** [comment]
The wallpapers usually keep changing after every few minutes and it is fetched in sorted order directly from Unsplash so yeas, sometimes the order might repeat itself.

**Comment by aebrer** [comment]
Good to know. Might be nice to blacklist skipped wallpapers.

Also would love to be able to specify a resolution. I'm getting a ton of weirdly stretched wallpapers.

**Comment by deepjyoti30** [comment]
I can do the blacklist thing. Maybe I'll add an option for resolution.

**Comment by aebrer** [comment]
Awesome! Love the app.

**Comment by deepjyoti30** [comment]
Added blacklist feature in [#3bdcb3](https://github.com/deepjyoti30/QuickWall/commit/3bdcb3ba72cea3100ea69b1d43e9773cf2023010)
