### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by ahmedselim2017** [deepjyoti30/QuickWall#12]
When I try to start it gives
```python
Traceback (most recent call last):
  File "/usr/bin/QuickWall", line 7, in <module>
    from QuickWall.SetPaper import SetPaper
ModuleNotFoundError: No module named 'QuickWall'
```
error.(installed from aur, wm is i3, python version is 3.8)

**Comment by deepjyoti30** [comment]
@ahmedselim2017 Are you sure your installation was succesfull? Can you try uninstalling and installing again?

Also tell me the version using ```--version```

**Comment by ahmedselim2017** [comment]
Yes, it was successful. I reinstall it but nothing changed. The output of ```--version`` is the same error.
```
~ ❯ QuickWall --version                                                                                                                                             19:37:39
Traceback (most recent call last):
  File "/usr/bin/QuickWall", line 7, in <module>
    from QuickWall.SetPaper import SetPaper
ModuleNotFoundError: No module named 'QuickWall'
```

**Comment by deepjyoti30** [comment]
@ahmedselim2017 Were you able to fix this issue with the newer versions? Closing since stale, you can reopen if you can provide any other input.

I would suggest trying out the latest version.
