### ISSUE TITLE
PKGBUILD has nitrogen as dependency

### ISSUE THREAD

**Issue by LeafyLappa** [deepjyoti30/QuickWall#16]
AUR package has nitrogen as dependency, it isn't optional. I'm running Manjaro Xfce and I suppose there's no actual need for nitrogen unless it's explicitly run from the code by default?

**Comment by deepjyoti30** [comment]
@Greentaily Yes, you're right. I think I forgot to remove it. I will do that in the next release perhaps.!

**Comment by deepjyoti30** [comment]
@Greentaily Should be fixed now. Made `nitrogen` optional dependency
