### ISSUE TITLE
QuickWall expects `feh` to have previously initialized

### ISSUE THREAD

**Issue by space-shell** [deepjyoti30/QuickWall#17]
I had installed `feh` with `QuickWall` together and upon the first run of `QuickWall` there were errors thrown about missing files related to `feh`.

The error raised was a python missing file error that was looking for a `.fehbg` file. In this case the file in question was only missing because I hadn't previously run `feh`.

After running `feh` and setting a placeholder background, `QuickWall` was working as expected.

**Comment by deepjyoti30** [comment]
@space-shell Thanks for the update. I mostly use `nitrogen` with `QuickWall` and hence never faced that issue. I will try to fix it soon.

**Comment by deepjyoti30** [comment]
Added in v0.0.5 release
