### ISSUE TITLE
Feature request: Option to specify a different target directory for downloads

### ISSUE THREAD

**Issue by sjsivert** [deepjyoti30/QuickWall#2]
Just makes it easier if you want to save these wallpapers in your collection for later use:)
Love the program!

**Comment by deepjyoti30** [comment]
I'll add an option to specify the directory.

**Comment by deepjyoti30** [comment]
Feature added in [#1e20e9](https://github.com/deepjyoti30/QuickWall/commit/1e20e9925d828fba1cedc697cb9411c7a00692cf)
