### ISSUE TITLE
Unauthorized error when fetching wallapapers from Unsplash

### ISSUE THREAD

**Issue by joajfreitas** [deepjyoti30/QuickWall#20]
![image](https://user-images.githubusercontent.com/16975424/153726630-3b57631c-2225-4c19-a373-16360dad8c6e.png)

Does the unsplash API require some form of authentication?

I've used quickwall both from the AUR package and from PyPi. The error is the same for the two versions.

**Comment by deepjyoti30** [comment]
Hey @joajfreitas thanks for reporting the issue. There was some issue with an upstream server, fixed the issue, will make a release soon.

In the meantime you can test out the `unstable` branch.

**Comment by deepjyoti30** [comment]
Added in v0.0.5 release
