### ISSUE TITLE
terminal colors lost on new window

### ISSUE THREAD

**Issue by DodgyDave** [deepjyoti30/QuickWall#22]
This tool is really cool, thanks for putting it together for us.  I use it on gnome, and whenever I open a new terminal it reverts back to the default palette.  Is there a way to make it persist?

**Comment by deepjyoti30** [comment]
I have not seen that behaviour before, will need more details to debug what exactly is going on.

The theme is set through `pywal` so this might be a better question in that community though as I said more details will be needed to debug it. Perhaps details like if you are using x-org etc will be useful.

**Comment by DodgyDave** [comment]
Thanks for the pointer to pywal.  I found the solution here:
https://github.com/dylanaraps/pywal/wiki/Getting-Started#applying-the-theme-to-new-terminals
