### ISSUE TITLE
Getting "IndexError: list index out of range" when using feh

### ISSUE THREAD

**Issue by ltgouvea** [deepjyoti30/QuickWall#4]
If I run `QuickWall` without arguments it works showing just a couple Gtk warnings which I don't think are related to QuickWall on its own. I'm on Linux Mint 19.2 with Cinnamon. Here's the output using feh:
```
➜  ~ QuickWall --setter feh
[Setter]: Using feh as wallpaper setter
Traceback (most recent call last):
  File "/usr/local/bin/QuickWall", line 119, in <module>
    main()
  File "/usr/local/bin/QuickWall", line 104, in main
    setter = wall_setter.get_setter()
  File "/usr/local/lib/python3.6/dist-packages/QuickWall/setter.py", line 36, in get_setter
    return self.setter()
  File "/usr/local/lib/python3.6/dist-packages/QuickWall/feh.py", line 16, in __init__
    self.current = self._find_current()
  File "/usr/local/lib/python3.6/dist-packages/QuickWall/feh.py", line 22, in _find_current
    return open(self.feh_config_path).read().split(' ')[4]
IndexError: list index out of range
```

The warnings shown after the wallpaper is set just by running `QuickWall`:

```
Gtk-Message: 19:26:59.369: Failed to load module "appmenu-gtk-module"
UNKNOWN ROOT WINDOW TYPE DETECTED (Nemo-desktop), please file a bug
Save this wallpapers? [Y]es [N]o [E]xit y
Gtk-Message: 19:27:02.695: Failed to load module "appmenu-gtk-module"
UNKNOWN ROOT WINDOW TYPE DETECTED (Nemo-desktop), please file a bug
```

**Comment by deepjyoti30** [comment]
@ltgouvea Sorry for the late reply.

Can you paste your ```~/.fehbg``` please?

Seems like fixed in the last commit. Can you check by fetching the latest commit?

**Comment by ltgouvea** [comment]
No problem, @deepjyoti30 :D Here's my current `.fehbg`
```
#!/bin/sh
'feh' '--bg-scale' '/home/k2/Pictures/Wallpapers/61.png' 
```

I fetched the last commit and reinstalled, and now this is the error I get

```
Traceback (most recent call last):
  File "/usr/local/bin/QuickWall", line 4, in <module>
    __import__('pkg_resources').run_script('QuickWall==0.0.1.post3', 'QuickWall')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/QuickWall' not found in metadata at '/usr/local/lib/python3.6/dist-packages/QuickWall-0.0.1.post3.dist-info'
```

**Comment by deepjyoti30** [comment]
That error is probably an installation issue.

Looking at your fehbg, the error is probably fixed in this commit.

For this installation issue, can you uninstall QuickWall using ```sudo pip uninstall QuickWall``` and then install it again using ```sudo python3 setup.py install```

**Comment by deepjyoti30** [comment]
@ltgouvea I looked into the installation error.

Please clone the latest commit, uninstall ```QuickWall``` and install it again and then run, it is probably fixed.

**Comment by ltgouvea** [comment]
@deepjyoti30 Excellent work man, everything is working fine now :)
I'm closing this issue, thank you very much for your help!
