### ISSUE TITLE
Add support for Plasmashell (KDE Plasma)

### ISSUE THREAD

**Issue by mikebell** [deepjyoti30/QuickWall#7]
I really love the idea of this tool. It'd be great if you supported plasmashell.

ksetwallpaper from https://gitlab.com/RaitaroH/KDE-Terminal-Wallpaper-Changer works as a script to change your wallpaper so that might be useful.

**Comment by deepjyoti30** [comment]
@mikebell Are you using KDE? It'd be great if you could help me test it out.

I have pushed initial support for KDE, can you please test and tell me if it's working.

Clone the repo and install using ```python setup.py install```. Haven't pushed it to anywhere else yet.

If you get any errors, give me the ```~/.cache/QuickWall/logs/log.cat``` and if everything works, tell me what you think about this feature.

**Comment by deepjyoti30** [comment]
Added in #9

**Comment by mikebell** [comment]
I'm getting the following while trying to install:

```
Installed /usr/local/lib/python3.6/dist-packages/pywal-3.3.0-py3.6.egg
Searching for downloader-cli
Reading https://pypi.python.org/simple/downloader-cli/
Downloading https://files.pythonhosted.org/packages/cf/54/f0143f1116cf1a6a78e4d2de5cbdbc127fe1d6fc9f607775725ab5236fc3/downloader_cli-0.1.0.tar.gz#sha256=7b8637b1023949100808fcfbcca404ea8c42174d95e531e52b1b04ec9506653b
Best match: downloader-cli 0.1.0
Processing downloader_cli-0.1.0.tar.gz
Writing /tmp/easy_install-783ense6/downloader_cli-0.1.0/setup.cfg
Running downloader_cli-0.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-783ense6/downloader_cli-0.1.0/egg-dist-tmp-rvkbj8e5
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
zip_safe flag not set; analyzing archive contents...
Moving downloader_cli-0.1.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding downloader-cli 0.1.0 to easy-install.pth file
Installing dw script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/downloader_cli-0.1.0-py3.6.egg
error: urllib3 1.25.3 is installed but urllib3>=1.25.6 is required by {'downloader-cli'}
```

**Comment by deepjyoti30** [comment]
Hey @mikebell , try installing using ```pip```. It should be fixed now. I've rolled an update for ```downloader-cli```
